# -*- coding: utf-8 -*-
"""emotions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r-tIA57I_itkVzt-gvObJNbFvRNgPb5A
"""

pip install deepface

import cv2
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()
image = cv2.imread('count_faces.jpg')

from deepface import DeepFace

faceDetect = cv2.CascadeClassifier(cv2.data.haarcascades  + "haarcascade_frontalface_default.xml")

gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
faces = faceDetect.detectMultiScale(gray_image, 1.1, 4)

for (x, y, w, h) in faces:
  cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)

for (x, y, w, h) in faces:
    roi_color = image[y:y+h, x:x+w]
    
    emotions = DeepFace.analyze(roi_color, actions=['emotion'], enforce_detection=False)
    print(emotions)
    emotion_label = emotions[0]['dominant_emotion']
    
    cv2.putText(image, emotion_label[0], (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

from google.colab.patches import cv2_imshow
cv2_imshow(image)

