# -*- coding: utf-8 -*-
"""pose.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gYOtDit5mc6XZaN_8tcux-Jauf28M1TW
"""

import deepface
from deepface import DeepFace
import cv2
import numpy as np

from google.colab import files
uploaded = files.upload()
image = cv2.imread('count_faces.jpg')

pose = DeepFace.analyze(image, actions=['multi_face_detection', 'pose'])

print(pose)
if "instance_face" in pose:
    for face in pose[0]["instance_face"]:
        pose = face["dominant_pose"]
        print("Face ID: ", face["instance_id"])
        print("Yaw (in degrees): ", pose["yaw"])
        print("Pitch (in degrees): ", pose["pitch"])
        print("Roll (in degrees): ", pose["roll"])
else:
    pose = pose[0]["X"]
    print("Yaw (in degrees): ", pose["yaw"])
    print("Pitch (in degrees): ", pose["pitch"])
    print("Roll (in degrees): ", pose["roll"])

